spring:
  datasource:
    url: "${DB_URL}"
    username: "${DB_USER}"
    password: "${DB_PASS}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # REMEBER TO CHANGE TO UPDATE LATER
      ddl-auto: create-drop
    show-sql: true
server:
  port: 6969
